# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: fjira
    main: ./cmd/fjira-cli
    binary: fjira
release:
  github:
    owner: mk-5
    name: fjira
  draft: true
  mode: replace
  header: |
    ## Release ({{ .Version }})
brews:
  - name: fjira
    tap:
      owner: mk-5
      name: homebrew-mk-5
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    url_template: "https://github.com/mk-5/fjira/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: mk-5
      email: mateusz+goreleaser@mk5.pl
    commit_msg_template: "misc: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/mk-5/fjira"
    license: "AGPL-3.0"
archives:
  - id: fjira
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
nfpms:
  - id: linux_packages
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: "mk-5"
    homepage: "https://github.com/mk-5/fjira"
    maintainer: "Mateusz <mateusz@mk5.pl>"
    description: "Fjira - the fuzziest Jira command line tool in the world."
    license: "AGPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    builds:
      - fjira
    scripts:
      postremove: "scripts/postremove.sh"
    rpm:
      signature:
        key_file: '{{ .Env.HOME }}/.key'
    deb:
      signature:
        key_file: '{{ .Env.HOME }}/.key'
# chocolateys:
#   -
#     name: fjira
#     ids:
#       - fjira
#     owners: mk5
#     title: Fjira - the fuzziest Jira command line tool in the world.
#     authors: mk5
#     project_url: https://github.com/mk-5/fjira
#     url_template: "https://github.com/mk-5/fjira/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     icon_url: 'https://github.com/mk-5/fjira/blob/master/fjira.png'
#     copyright: 2022 mk-5
#     license_url: https://github.com/mk-5/fjira/blob/master/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/mk-5/fjira
#     docs_url: https://github.com/mk-5/fjira/blob/master/README.md
#     bug_tracker_url: https://github.com/mk-5/fjira/issues
#     tags: "fjira jira terminal tui"
#     summary: Terminal application to deal with Atlassian Jira.
#     description: |
#       {{ .ProjectName }} installer package.
#       Terminal application to deal with Atlassian Jira.
#     release_notes: "https://github.com/mk-5/fjira/releases/tag/v{{ .Version }}"
#     api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
#     source_repo: "https://push.chocolatey.org/"
#     goamd64: v1
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^refactor:'
