# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: fjira
    main: ./cmd/fjira-cli
    binary: fjira
release:
  github:
    owner: mk-5
    name: fjira
  draft: true
  mode: replace
  header: |
    ## Release ({{ .Version }})
brews:
  - name: fjira
    tap:
      owner: mk-5
      name: homebrew-mk-5
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    url_template: "https://github.com/mk-5/fjira/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: mk-5
      email: mateusz+goreleaser@mk5.pl
    commit_msg_template: "misc: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/mk-5/fjira"
    license: "AGPL-3.0"
archives:
  - id: fjira
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
nfpms:
  - id: linux_packages
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: "mk-5"
    homepage: "https://github.com/mk-5/fjira"
    maintainer: "Mateusz <mateusz@mk5.pl>"
    description: "Fjira - the fuzziest Jira command line tool in the world."
    license: "AGPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    builds:
      - fjira
    scripts:
      postremove: "scripts/postremove.sh"
    rpm:
      signature:
        key_file: '{{ .Env.HOME }}/.key'
    deb:
      signature:
        key_file: '{{ .Env.HOME }}/.key'
snapcrafts:
  -
    id: fjira
    builds:
      - fjira
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name: fjira
    title: Fjira
    disable: false
    publish: true
    summary: Fuzzy finder and TUI application for Jira.
    description: |
          Fjira is a powerful terminal user interface (TUI) application designed to streamline your Jira workflow.
          With its fuzzy-find capabilities, it simplifies the process of searching and accessing Jira issues,
          making it easier than ever to locate and manage your tasks and projects efficiently.
          Say goodbye to manual searching and hello to increased productivity with fjira.
    channel_templates:
      - edge
      - beta
      - candidate
      - stable
    grade: stable
    confinement: strict
    license: "AGPL-3.0"
    base: core18
    assumes:
      - snapd2.38
    apps:
      fjira:
        # If your app requires extra permissions to work outside of its default
        # confined space, declare them here.
        # You can read the documentation about the available plugs and the
        # things they allow:
        # https://snapcraft.io/docs/supported-interfaces.
        plugs: ["home", "network", "network-bind"]

aurs:
  - name: fjira
    homepage: https://github.com/mk-5/fjira
    description: Fjira - the fuzziest Jira command line tool in the world
    maintainers:
      - 'Mateusz Kulawik <mateusz+aur@mk5.pl>'
      - 'Jonathan Neidel <aur at jneidel dot com>'
    license: 'AGPL3'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/fjira.git'
    package: |-
      install -Dm755 "./fjira" "${pkgdir}/usr/bin/fjira"

chocolateys:
  -
    name: fjira
    ids:
      - fjira
    owners: mk5
    title: Fjira - the fuzziest Jira command line tool in the world.
    authors: mk5
    project_url: https://github.com/mk-5/fjira
    url_template: "https://github.com/mk-5/fjira/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: 'https://cdn.statically.io/gh/mk-5/fjira/60767ee5/fjira.png'
    copyright: 2022 mk-5
    license_url: https://github.com/mk-5/fjira/blob/master/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/mk-5/fjira
    docs_url: https://github.com/mk-5/fjira/blob/master/README.md
    bug_tracker_url: https://github.com/mk-5/fjira/issues
    tags: "fjira jira terminal tui"
    summary: Terminal application to deal with Atlassian Jira.
    description: |
      {{ .ProjectName }} installer package.
      Fjira is a powerful terminal user interface (TUI) application designed to streamline your Jira workflow.
      With its fuzzy-find capabilities, it simplifies the process of searching and accessing Jira issues,
      making it easier than ever to locate and manage your tasks and projects efficiently.
      Say goodbye to manual searching and hello to increased productivity with fjira.
    release_notes: "https://github.com/mk-5/fjira/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    goamd64: v1

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^refactor:'
